name: RPGSkillsPlugin
version: 1.1
main: org.frizzlenpop.rPGSkillsPlugin.RPGSkillsPlugin
api-version: 1.21
author: Frizzlenpop
config-yml: config.yml

commands:
  skills:
    description: Opens the skills menu.
    usage: /skills
    permission: rpgskills.use
  passives:
    description: Opens the passive skills menu.
    usage: /passives
    permission: rpgskills.passive
  miningburst:
    description: Activates the Mining Burst ability.
    usage: /miningburst
    permission: rpgskills.miningburst
  timberchop:
    description: Activates the Timber Chop ability.
    usage: /timberchop
    permission: rpgskills.timberchop
  berserkerrage:
    description: Activates the Berserker Rage ability.
    usage: /berserkerrage
    permission: rpgskills.berserkerrage
  superharvest:
    description: Activates the Super Harvest ability
    usage: /superharvest
    permission: rpgskills.superharvest
  instantcatch:
    description: Activates the Instant Catch ability
    usage: /instantcatch
    permission: rpgskills.instantcatch
  doubleenchant:
    description: Activates the Double Enchant ability
    usage: /doubleenchant
    permission: rpgskills.doubleenchant
  toggleskillmessages:
    description: Toggle skill-related messages on/off
    usage: /toggleskillmessages
  skillsadmin:
    description: Admin commands for managing skills
    usage: /skillsadmin <player> <skill> <set/add> <level/xp> <amount>
    permission: rpgskills.admin
  abilities:
    description: Activate skill abilities
    usage: /abilities <skill>